kind: Deployment
apiVersion: apps/v1
metadata:
  name: web
spec:
  replicas: 2
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      k8s-app: web
  template:
    metadata:
      labels:
        k8s-app: web
    spec:
      containers:
        - name: web
          image: ankur512512/argocd-nginx:88b5d37bfa74ce887c7a3fde95157fb16e0aa5ad
          imagePullPolicy: Always
          ports:
            - containerPort: 80
              protocol: TCP
