apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: demoapp-web-ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
    kubernetes.io/ingress.class: "nginx"
    alb.ingress.kubernetes.io/ssl-passthrough: "true"
    nginx.ingress.kubernetes.io/force-ssl-redirect: "false"
spec:
  tls:
  - hosts:
    - ak.webhop.me
    secretName: ak-webhop-me
  rules:
  - http:
      paths:
      - pathType: Prefix
        path: /myapp
        backend:
          service:
            name: web
            port:
              number: 443
    host: ak.webhop.me
